#
# Truma heater (smartavan-box)
# Hinter Truma Bedienteil
# ch341-uart converter now attached to ttyUSB4
#

esphome:
  name: "georg-smartavan"

external_components:
  #- source: github://Fabian-Schmidt/esphome-truma_inetbox
  #- source: github://BikeAtor/esphome-truma_inetbox@esp-idf_2025.11.0
  - source: github://BikeAtor/esphome-truma_inetbox@esp-idf_2026.4.3
    components: ["truma_inetbox", "uart"]
    refresh: always

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    #version: recommended
    version: 5.5.4

# fallback wifi
#captive_portal:

wifi:
  use_address: !secret wifi_smartavan_ip
  # If you want to define wifi and ip, do uncomment lines below (and)
  # wifi:
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #manual_ip:
  #  static_ip: ${wifi_smartavan_ip}
  #  gateway: ${wifi_gateway}
  #  subnet: 255.255.255.0
  #ap:

logger:

web_server:
  port: 80
  version: 3
  local: true
  ota: false

ota:
  - platform: esphome
    password: !secret ota_password

# If you want to use MQTT for communication, uncomment these and define
# MQTT broker details

# mqtt:
#   broker: 10.0.0.2
#   username: livingroom
#   password: password_here

# If you are not using Home Assistant integration, then comment out api: line
# Otherwise it will reboot every 15 minutes
api:

#esp32_ble_tracker:
#  scan_parameters:
#    # We currently use the defaults to ensure Bluetooth
#    # can co-exist with WiFi In the future we may be able to
#    # enable the built-in coexistence logic in ESP-IDF
#    active: true

#bluetooth_proxy:
#  active: true

#time:
#  - platform: homeassistant
#    id: real_time

# If you are not using Home Assistant, get time from SNTP
time:
  - platform: sntp
    id: real_time
    timezone: Europe/Berlin

uart:
  - id: lin_uart_bus
    tx_pin: 16
    rx_pin: 17
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

truma_inetbox:
  uart_id: lin_uart_bus
  time_id: real_time

climate:
  - platform: truma_inetbox
    name: "truma_room"
    type: ROOM
  - platform: truma_inetbox
    name: "truma_water"
    type: WATER

binary_sensor:
  - platform: truma_inetbox
    name: "truma_cp_plus_alive"
    type: CP_PLUS_CONNECTED
  - platform: truma_inetbox
    name: "truma_heater_has_error"
    type: HEATER_HAS_ERROR

sensor:
  - platform: truma_inetbox
    name: "truma_current_room_temperature"
    type: CURRENT_ROOM_TEMPERATURE
  - platform: truma_inetbox
    name: "truma_current_water_temperature"
    type: CURRENT_WATER_TEMPERATURE

select:
  - platform: truma_inetbox
    name: "truma_fan_mode"
    type: HEATER_FAN_MODE_COMBI
  - platform: truma_inetbox
    name: "truma_energy_mix"
    type: HEATER_ENERGY_MIX_GAS
